### ISSUE TITLE
Relative links in README's

### ISSUE THREAD

**Issue by JosefWN** [PaulZC/Artemis_Global_Tracker#1]
Hi, great work on the IoT!

I was just wondering if it would be possible to do a global search and remove (regex) on `https://github.com/PaulZC/Artemis_Global_Tracker/.*/master/` for `.md` files? That way, the docs would work in separate branches, and look better in cloned repos.

For example, to link to the Hardware overview, all it takes is a relative link: `Documentation/Hardware_Overview/README.md`.

Tried to make a PR, but couldn't push.

**Comment by PaulZC** [comment]
Hi @JosefWN ,
Thank you for the suggestion!
This repo will be moving over into the SparkFun repositories in the next day or two, so I will need to fix the links then.
It looks like you have not yet forked the repo? That is probably why you cannot submit your PR. It will save me some typing if you could do that - thanks!
If you do plan to clone the repo, please make sure you are complying with the CC BY-SA 4.0 licence.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi @JosefWN ,
I have updated the documentation links. I think I have changed all of them (apart from the ones that go to external sites). Please download and let me know if you notice any problems.
I am going to close this issue as I think it is resolved, but please reopen if I have missed anything.
Best wishes,
Paul
